services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-scripts/:/docker-entrypoint-initdb.d/
      #- ./mysql:/var/lib/mysql #Do not persist data
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SHOW TABLES;", "bank-app"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  account:
    build: 
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      CLIENT_SERVICE_BASE_URI: "http://client:8080/api"
      SERVICE_CLIENT_INFO: "/clientes/{id}"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 3306
    restart: always
    depends_on:
      - db
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 3306
    restart: always
    depends_on:
      - db